In [56]:
import pandas as pd # for manipulating data frames
import pingouin as pg # for running statistics
import plotly.express as px

In [36]:
data = pd.read_csv('lens_experiment/lens_experiment.csv', sep=';')
data

Participant  Block  Trial Lens  Magnification        ID  PointingTime
0                1      4      0   FL              6  6.003555          2297
1                1      4      0   FL              6  6.003555          1485
2                1      4      0   FL              6  6.003555          2000
3                1      4      0   FL              6  6.003555          1843
4                1      4      0   FL              6  6.003555          1813
...            ...    ...    ...  ...            ...       ...           ...
11995           10      2      9  SCF              6  6.003555          2313
11996           10      2      9  SCF              6  6.003555          2453
11997           10      2      9  SCF              6  6.003555          2187
11998           10      2      9  SCF              6  6.003555          2875
11999           10      2      9  SCF              6  6.003555          2688

[12000 rows x 7 columns]

In [8]:
data['Participant']

0         1
1         1
2         1
3         1
4         1
         ..
11995    10
11996    10
11997    10
11998    10
11999    10
Name: Participant, Length: 12000, dtype: int64

In [6]:
data.iloc[2]

Participant             1
Block                   4
Trial                   0
Lens                   FL
Magnification           6
ID               6.003555
PointingTime         2000
Name: 2, dtype: object

In [10]:
data.dtypes

Participant        int64
Block              int64
Trial              int64
Lens              object
Magnification      int64
ID               float64
PointingTime       int64
dtype: object

Participant should not be int. It is actually an identifier. Let's turn it into str.

In [87]:
data['Participant'] = data['Participant'].astype('str')
data.dtypes

Participant                            object
Block                                   int64
Trial                                   int64
Lens                                   object
Magnification                           int64
ID                                    float64
PointingTime                            int64
Condition: Lens, Magnification, ID     object
dtype: object

In [12]:
data_fl = data.query('Lens == \'FL\'') # filter out data to get only data for the Lens=FL condition
data_fl

Participant  Block  Trial Lens  Magnification        ID  PointingTime
0                1      4      0   FL              6  6.003555          2297
1                1      4      0   FL              6  6.003555          1485
2                1      4      0   FL              6  6.003555          2000
3                1      4      0   FL              6  6.003555          1843
4                1      4      0   FL              6  6.003555          1813
...            ...    ...    ...  ...            ...       ...           ...
11035           10      3      9   FL              6  6.003555          2547
11036           10      3      9   FL              6  6.003555          1797
11037           10      3      9   FL              6  6.003555          1656
11038           10      3      9   FL              6  6.003555          1312
11039           10      3      9   FL              6  6.003555          2282

[2400 rows x 7 columns]

In [37]:
data.describe(include = 'all')

Participant         Block         Trial   Lens  Magnification  \
count   12000.000000  12000.000000  12000.000000  12000   12000.000000   
unique           NaN           NaN           NaN      5            NaN   
top              NaN           NaN           NaN     FL            NaN   
freq             NaN           NaN           NaN   2400            NaN   
mean        5.500000      3.000000      4.500000    NaN       7.200000   
std         2.872401      1.414272      2.872401    NaN       4.308311   
min         1.000000      1.000000      0.000000    NaN       2.000000   
25%         3.000000      2.000000      2.000000    NaN       4.000000   
50%         5.500000      3.000000      4.500000    NaN       6.000000   
75%         8.000000      4.000000      7.000000    NaN      10.000000   
max        10.000000      5.000000      9.000000    NaN      14.000000   

                  ID  PointingTime  
count   12000.000000  12000.000000  
unique           NaN           NaN  
top              NaN           NaN  
freq             NaN           NaN  
mean        6.112107   2561.142083  
std         1.327710   1828.979452  
min         4.200952    766.000000  
25%         5.288921   1500.000000  
50%         6.003555   2000.000000  
75%         7.069674   2969.000000  
max         7.997436  32906.000000

<code>Pandas</code> propose several functions for aggregating a dataframe: <code>mean</code>, <code>min</code>, <code>max</code>, <code>sum</code>, etc. 

In [13]:
### Applying them to a column gives a result of type series
data.PointingTime.mean()

2561.142083333333

In [15]:
### We can get a breakdown by condition using the groupby function
data.groupby('Lens').PointingTime.mean()

Lens
BL     2666.405417
FL     2399.813750
ML     3498.588750
SCB    1881.055417
SCF    2359.847083
Name: PointingTime, dtype: float64

In [9]:
### Applying those aggregating functions to a dataframe gives a result of type dataframe
data.groupby('Lens').mean() # result is a dataframe

Participant  Block  Trial  Magnification        ID  PointingTime
Lens                                                                  
BL            5.5    3.0    4.5            7.2  6.112107   2666.405417
FL            5.5    3.0    4.5            7.2  6.112107   2399.813750
ML            5.5    3.0    4.5            7.2  6.112107   3498.588750
SCB           5.5    3.0    4.5            7.2  6.112107   1881.055417
SCF           5.5    3.0    4.5            7.2  6.112107   2359.847083

In [10]:
### aggregate is a more elaborate aggregate function
# the line below is equivalent to: data.groupby('Lens').mean()
# data.groupby('Lens').aggregate('mean') 
# but here aggregate is used to specify how to aggregate different columns
data.groupby('Lens').aggregate({'Trial': 'sum', 'PointingTime': 'mean'}) 

Trial  PointingTime
Lens                     
BL    10800   2666.405417
FL    10800   2399.813750
ML    10800   3498.588750
SCB   10800   1881.055417
SCF   10800   2359.847083

In [18]:
d = {'id':[1,3,4],'starttime': [124, 357, 489], 'endtime': [202, 476, 604]}
df = pd.DataFrame(data=d)
df

id  starttime  endtime
0   1        124      202
1   3        357      476
2   4        489      604

In [22]:
df['completiontime'] = df['endtime'] - df['starttime']
df.loc[df['id'] <= 3, 'difficulty'] = 'easy'
df.loc[df['id'] > 3, 'difficulty'] = 'medium'
df

id  starttime  endtime  completiontime difficulty
0   1        124      202              78       easy
1   3        357      476             119       easy
2   4        489      604             115     medium

# <span style='color:blue'>Descriptive statistics</span>

When designing an experiment, a good sanity check consists of looking at the number of observations (trials) per experimental condition to double check that we actually have the same number of observations per condition (*i.e.*, our design is properly **balanced**).

In [40]:
# make a copy of column Magnification and change its type from int to str
magAsStr = data['Magnification'].copy().astype('str')
# make a copy of column ID and change its type from float to str
idAsStr = data['ID'].copy().astype('str')
# now that we have strings, we can concatenate them using function 'cat'
data['Condition: Lens, Magnification, ID'] = data['Lens'].str.cat(magAsStr.str.cat(idAsStr, sep=", "), sep=", ")
data

Participant  Block  Trial Lens  Magnification        ID  PointingTime  \
0                1      4      0   FL              6  6.003555          2297   
1                1      4      0   FL              6  6.003555          1485   
2                1      4      0   FL              6  6.003555          2000   
3                1      4      0   FL              6  6.003555          1843   
4                1      4      0   FL              6  6.003555          1813   
...            ...    ...    ...  ...            ...       ...           ...   
11995           10      2      9  SCF              6  6.003555          2313   
11996           10      2      9  SCF              6  6.003555          2453   
11997           10      2      9  SCF              6  6.003555          2187   
11998           10      2      9  SCF              6  6.003555          2875   
11999           10      2      9  SCF              6  6.003555          2688   

      Condition: Lens, Magnification, ID  
0                       FL, 6, 6.0035549  
1                       FL, 6, 6.0035549  
2                       FL, 6, 6.0035549  
3                       FL, 6, 6.0035549  
4                       FL, 6, 6.0035549  
...                                  ...  
11995                  SCF, 6, 6.0035549  
11996                  SCF, 6, 6.0035549  
11997                  SCF, 6, 6.0035549  
11998                  SCF, 6, 6.0035549  
11999                  SCF, 6, 6.0035549  

[12000 rows x 8 columns]

In [43]:
data.groupby('Participant').count()

Block  Trial  Lens  Magnification    ID  PointingTime  \
Participant                                                          
1             1200   1200  1200           1200  1200          1200   
2             1200   1200  1200           1200  1200          1200   
3             1200   1200  1200           1200  1200          1200   
4             1200   1200  1200           1200  1200          1200   
5             1200   1200  1200           1200  1200          1200   
6             1200   1200  1200           1200  1200          1200   
7             1200   1200  1200           1200  1200          1200   
8             1200   1200  1200           1200  1200          1200   
9             1200   1200  1200           1200  1200          1200   
10            1200   1200  1200           1200  1200          1200   

             Condition: Lens, Magnification, ID  
Participant                                      
1                                          1200  
2                                          1200  
3                                          1200  
4                                          1200  
5                                          1200  
6                                          1200  
7                                          1200  
8                                          1200  
9                                          1200  
10                                         1200

The <code>histogram</code> function from library <code>plotly</code> visualizes distributions. See https://plotly.com/python/histograms/.

In [53]:
fig = px.histogram(data, x='Condition: Lens, Magnification, ID', color='Participant')
fig.show()

# If needed (e.g., for inclusion in a report), we can save the last plot as a PDF file
fig.write_image('images/counts_per_condition.pdf')

In [48]:
fig = px.histogram(data, x='PointingTime')
fig.show()

fig.write_image('images/pointingtime_distribution.pdf')

We can add a box plot to complement the histogram.

In [51]:
fig = px.histogram(data, x='PointingTime', marginal='box')
fig.show()

fig.write_image('images/pointingtime_distribution_with_box.pdf')

Let's look at a breakdown per *Lens* condition:

In [52]:
fig = px.histogram(data, x='PointingTime', color='Lens', marginal='box')
fig.show()

fig.write_image('images/pointingtime_distribution_with_box_per_lens.pdf')

We can also 'spread' the histogram by using a logarithimc scale to better visualize what happens for low values where most observations lie in our case:

In [55]:
fig = px.histogram(data, x='PointingTime', color='Lens', marginal='box', log_x=True)
fig.show()

fig.write_image('images/pointingtime_distribution_with_box_per_lens_log.pdf')

# <span style='color:blue'>Inferential statistics</span>

In [88]:
correlation_table = pg.pairwise_corr(data, columns=['Magnification','PointingTime'])
correlation_table

X             Y   method alternative      n         r  \
0  Magnification  PointingTime  pearson   two-sided  12000  0.622792   

          CI95%  p-unc BF10  power  
0  [0.61, 0.63]    0.0  inf    1.0

r is 0.6 (and p<0.001) so there is a positive relation between variables PointingTime and Magnification. Note that we usually report r<sup>2</sup>

In [89]:
r2 = correlation_table['r'] * correlation_table['r']
r2

0    0.38787
Name: r, dtype: float64

We found a correlation between ID and PointingTime (r<sup>2</sup>(12000) = 0.6, p < 0.001).

It is also common practice to look at the correlation between two variables after having aggregated observations within experimental conditions. For example, we can consider only one mean PointingTime per IDxLensxMagnification for each participant (aggregating replications). Aggregating removes variance and thus mechanically increases the correlation coefficient. There is no best solution between aggregating and not aggregating. What is important is to make it clear if data were aggregated or not by reporting the number of observations (n) considered in the correlation analysis so that readers know how to interpret the results.

In [97]:
data_agg = data.groupby(['Participant', 'ID', 'Lens', 'Magnification'], as_index=False)['PointingTime'].mean()
data_agg

Participant        ID Lens  Magnification  PointingTime
0             1  4.200952   BL              2   1222.020833
1             1  4.200952   FL              2   1233.729167
2             1  4.200952   ML              2   1017.583333
3             1  4.200952  SCB              2   1311.208333
4             1  4.200952  SCF              2   1311.854167
..          ...       ...  ...            ...           ...
245           9  7.997436   BL             14   4586.583333
246           9  7.997436   FL             14   4038.416667
247           9  7.997436   ML             14   6621.750000
248           9  7.997436  SCB             14   2574.229167
249           9  7.997436  SCF             14   4364.250000

[250 rows x 5 columns]

In [98]:
correlation_table = pg.pairwise_corr(data_agg, columns=['Magnification','PointingTime'])
correlation_table

X             Y   method alternative    n         r  \
0  Magnification  PointingTime  pearson   two-sided  250  0.782979   

          CI95%         p-unc       BF10  power  
0  [0.73, 0.83]  4.762157e-53  4.195e+49    1.0

We found a correlation between ID and PointingTime (r<sup>2</sup>(250) = 0.75, p < 0.001).

In [99]:
lm = pg.linear_regression(data_agg['Magnification'], data_agg['PointingTime'])
lm

names        coef          se          T          pval        r2  \
0      Intercept  657.534174  111.912728   5.875419  1.351668e-08  0.613056   
1  Magnification  264.389987   13.338075  19.822200  4.762157e-53  0.613056   

     adj_r2   CI[2.5%]   CI[97.5%]  
0  0.611496  437.11359  877.954758  
1  0.611496  238.11964  290.660335

After having aggregated our observations per ID x participant, we found a correlation between ID and PointingTime (r<sup>2</sup>(250) = 0.38, p < 0.001), with Magnification being a predictor of PointingTime with the following regression model: PointingTime = 657 + 264 x ID.

We use function <code>scatter</code> from <code>plotly</code> to display the relation between Magnification and PointingTime in the form of a scatterplot with the regression line on top.

In [102]:
fig = px.scatter(
    data_agg, x='Magnification', y='PointingTime', opacity=0.65,
    trendline='ols'
)
fig.show()

fig.write_image('images/linear_regression_PointingTime_Magnification.pdf')

We can also look at how PointingTime gets impacted by Magnification factor with different lenses.

In [103]:
fig = px.scatter(
    data_agg, x='Magnification', y='PointingTime', opacity=0.65,
    trendline='ols', color='Lens'
)
fig.show()

This suggests that ML lenses are more impacted by an increasing Magnification factor.

## Analyzing the effect of one nominal factor with only two levels on a continuous measure: t-test

We use the lens_experiment dataset. We will compare two types of lenses (FL lenses and ML lenses) regarding pointing time. Although this dataset corresponds to a study where five different lenses were compared, we use data collected in the FL and ML conditions for the purpose of illustration.

We run a **t-test** to test the effect of factor *Lens* (two levels: {*FL*, *ML*}) on measure *PointingTime*. A paired t-test takes as input two vector of data points. There is one vector per condition (in our case: *FL* and *ML*), and each vector contains the mean measure value for each participant (in our case, 10 mean pointing times as we have 10 participants):

Vector 1:
data_fl = (meantime_fl_p1, ...., meantime_fl_p10)

Vector 2:
data_ml = (meantime_ml_p1, ...., meantime_ml_p10)

In [106]:
data_fl = data.query('Lens == "FL"') # filter out data to get only data for the Lens=FL condition
data_fl = data_fl.groupby('Participant', as_index=False)['PointingTime'].mean() # aggregate lines to get only one line per participant that contains the mean pointing time for that participant
display(data_fl)
data_ml = data.query('Lens == "ML"')
data_ml = data_ml.groupby('Participant', as_index=False)['PointingTime'].mean()
display(data_ml)

Participant  PointingTime
0           1   2234.900000
1          10   2349.350000
2           2   2401.108333
3           3   2721.108333
4           4   2412.704167
5           5   2171.679167
6           6   2359.762500
7           7   2586.983333
8           8   2482.025000
9           9   2278.516667

Participant  PointingTime
0           1   3091.016667
1          10   3899.479167
2           2   3429.166667
3           3   4932.154167
4           4   3533.025000
5           5   3261.845833
6           6   3284.375000
7           7   3277.541667
8           8   3205.920833
9           9   3071.362500

In [107]:
# compute ttest to compare the 'PointingTime' between FL and ML conditions
ttest = pg.ttest(data_fl['PointingTime'], data_ml['PointingTime'], paired=True)
ttest

T  dof alternative     p-val                CI95%   cohen-d  \
T-test -7.490894    9   two-sided  0.000037  [-1430.59, -766.96]  2.669193   

          BF10  power  
T-test  664.76    1.0

In [108]:
mean_fl = data_fl['PointingTime'].mean()
mean_ml = data_ml['PointingTime'].mean()
print('Mean pointing time for Lens=FL: ', mean_fl)
print('Mean pointing time for Lens=ML: ', mean_ml)

Mean pointing time for Lens=FL:  2399.8137500000003
Mean pointing time for Lens=ML:  3498.5887500000003


**Formal report for the test**: A paired t-test revealed a significant effect of the type of lenses on pointing time (*t*(1,9)=-7.4, *p* < 0.001, Cohen's *d* = 2.7), with FL lenses outperforming ML lenses (2400ms and 3499ms on average respectively).

## Analyzing the effect of one nominal factor with more than two levels on a continuous measure

In this case, we run a **one-way repeated measures anova**.

With a t-test (as above), we were able to compare only two types of lenses. Here, with an anova test, we can compare the five types of lenses with a single test.

In [110]:
aovrm1way = pg.rm_anova(data=data, dv='PointingTime', within='Lens', subject='Participant')
aovrm1way

Source  ddof1  ddof2          F         p-unc  p-GG-corr       ng2  \
0   Lens      4     36  62.408495  1.077454e-15   0.000001  0.794287   

        eps  sphericity   W-spher   p-spher  
0  0.337259       False  0.004401  0.000011

Based on the anova report, we can see that *Lens* has a significant effect on *PointingTime* (F(4,36) = 62, p < 0.001). However, we don't know which types of lenses actually differ. Maybe only one type of lenses is significantly faster than the four other ones but the four other ones have similar performance? Maybe they all significantly differ from each other?... We can't say based on the sole anova report. To get details about pairs that actually differ, we should run **post-hoc tests**:

In [111]:
posthoc = pg.pairwise_tests(data=data, dv='PointingTime', within=['Lens'], subject='Participant', parametric=True, padjust='fdr_bh', effsize='hedges')
posthoc

Contrast    A    B  Paired  Parametric          T  dof alternative  \
0     Lens   BL   FL    True        True   4.345090  9.0   two-sided   
1     Lens   BL   ML    True        True  -5.614069  9.0   two-sided   
2     Lens   BL  SCB    True        True  31.577207  9.0   two-sided   
3     Lens   BL  SCF    True        True   6.595215  9.0   two-sided   
4     Lens   FL   ML    True        True  -7.490894  9.0   two-sided   
5     Lens   FL  SCB    True        True   9.341874  9.0   two-sided   
6     Lens   FL  SCF    True        True   0.645461  9.0   two-sided   
7     Lens   ML  SCB    True        True   9.851450  9.0   two-sided   
8     Lens   ML  SCF    True        True   6.786651  9.0   two-sided   
9     Lens  SCB  SCF    True        True -11.895149  9.0   two-sided   

          p-unc        p-corr p-adjust       BF10    hedges  
0  1.863562e-03  2.070625e-03   fdr_bh     24.371  1.552562  
1  3.283107e-04  4.103884e-04   fdr_bh    104.046 -1.936085  
2  1.572325e-10  1.572325e-09   fdr_bh  3.503e+07  5.194532  
3  9.982369e-05  1.426053e-04   fdr_bh    285.907  1.777954  
4  3.728208e-05  7.456416e-05   fdr_bh     664.76 -2.556411  
5  6.287323e-06  1.571831e-05   fdr_bh   3096.594  3.432268  
6  5.347356e-01  5.347356e-01   fdr_bh      0.368  0.231850  
7  4.052381e-06  1.350794e-05   fdr_bh   4536.747  3.832725  
8  8.025315e-05  1.337553e-04   fdr_bh    344.493  2.647644  
9  8.297272e-07  4.148636e-06   fdr_bh  1.812e+04 -3.151003

In [113]:
import math

def summarizeDF(df, factors, measure):
    summary = data.groupby(factors, as_index=False)[measure].aggregate({'Mean': 'mean', 'Count': 'count', 'Std':'std'})
    ci95_hi = []
    ci95_lo = []
    for i in summary.values:
        mean, count, std = i[len(factors)], i[len(factors)+1], i[len(factors)+2]
        ci95_hi.append(mean + 1.96*std/math.sqrt(count))
        ci95_lo.append(mean - 1.96*std/math.sqrt(count))

    summary['ci95_hi'] = ci95_hi
    summary['ci95_lo'] = ci95_lo
    return summary

In [114]:
stats = summarizeDF(data, ['Lens'], 'PointingTime')
stats

Lens         Mean  Count          Std      ci95_hi      ci95_lo
0   BL  2666.405417   2400  1400.267213  2722.427773  2610.383060
1   FL  2399.813750   2400  1266.792679  2450.496013  2349.131487
2   ML  3498.588750   2400  3156.100429  3624.859065  3372.318435
3  SCB  1881.055417   2400   658.170719  1907.387730  1854.723104
4  SCF  2359.847083   2400  1162.838646  2406.370318  2313.323848

In [116]:
nice_color_palette = ['#66c2a5', '#fc8d62', '#8da0cb', '#e78ac3', '#a6d854']

fig = px.bar(stats, x='Lens', y='Mean', color='Lens', color_discrete_sequence=nice_color_palette).update_traces(
    error_y={
        'type': 'data',
        'symmetric': False,
        'array': stats['ci95_hi'] - stats['Mean'],
        'arrayminus': stats['Mean'] - stats['ci95_lo'],
    }
)
fig.update_layout({
    'plot_bgcolor' : 'rgba(0,0,0,0)'
})
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGray')

fig.show()

fig.write_image('images/pointingtime_per_lens.pdf')

## Analyzing the effect of two nominal factors on a continuous measure

In this case, we run a **two-way repeated measures anova**.

With a one-way anova, we cannot detect if two factors interact with one another. A two-way anova will tell whether the effect of one factor is influenced by the other factor (interaction effect) or not.

In [119]:
aovrm2way = pg.rm_anova(data=data, dv='PointingTime', within=['Lens', 'Magnification'], subject='Participant')
aovrm2way

/opt/anaconda3/lib/python3.9/site-packages/pingouin/distribution.py:515: UserWarning:

Epsilon values might be innaccurate in two-way repeated measures design where each  factor has more than 2 levels. Please  double-check your results.



Source            SS  ddof1  ddof2            MS           F  \
0                  Lens  7.094755e+07      4     36  1.773689e+07   62.408495   
1         Magnification  3.302858e+08      4     36  8.257145e+07  666.205094   
2  Lens * Magnification  9.525647e+07     16    144  5.953529e+06   88.046197   

          p-unc     p-GG-corr       ng2       eps  
0  1.077454e-15  1.464553e-06  0.685343  0.337259  
1  3.309458e-33  6.874744e-14  0.910230  0.381525  
2  6.510501e-66  6.160824e-09  0.745180  0.108297

In [120]:
posthoc = pg.pairwise_tests(data=data, dv='PointingTime', within=['Lens','Magnification'], subject='Participant', parametric=True, padjust='holm', effsize='cohen')
posthoc

Contrast Lens   A    B Paired  Parametric          T  dof  \
0                   Lens    -  BL   FL   True        True   4.345090  9.0   
1                   Lens    -  BL   ML   True        True  -5.614069  9.0   
2                   Lens    -  BL  SCB   True        True  31.577207  9.0   
3                   Lens    -  BL  SCF   True        True   6.595215  9.0   
4                   Lens    -  FL   ML   True        True  -7.490894  9.0   
..                   ...  ...  ..  ...    ...         ...        ...  ...   
65  Lens * Magnification  SCF   4   10   True        True -22.218952  9.0   
66  Lens * Magnification  SCF   4   14   True        True -15.880462  9.0   
67  Lens * Magnification  SCF   6   10   True        True -10.006688  9.0   
68  Lens * Magnification  SCF   6   14   True        True -14.696120  9.0   
69  Lens * Magnification  SCF  10   14   True        True  -9.464705  9.0   

   alternative         p-unc        p-corr p-adjust       BF10     cohen  
0    two-sided  1.863562e-03  3.727124e-03     holm     24.371  1.621057  
1    two-sided  3.283107e-04  9.849320e-04     holm    104.046 -2.021501  
2    two-sided  1.572325e-10  1.572325e-09     holm  3.503e+07  5.423703  
3    two-sided  9.982369e-05  4.012658e-04     holm    285.907  1.856393  
4    two-sided  3.728208e-05  2.236925e-04     holm     664.76 -2.669193  
..         ...           ...           ...      ...        ...       ...  
65   two-sided  3.583086e-09  1.397403e-07     holm  2.196e+06 -7.360378  
66   two-sided  6.867329e-08  1.785506e-06     holm  1.618e+05 -6.375715  
67   two-sided  3.558379e-06  4.270055e-05     holm   5080.397 -3.137807  
68   two-sided  1.347383e-07  3.098980e-06     holm  8.937e+04 -4.902530  
69   two-sided  5.645498e-06  5.645498e-05     holm    3400.27 -3.634816  

[70 rows x 14 columns]

We can see above that pairwise t-tests quickly become difficult to read and interpret when the number of factors or/and the number of levels per factor increase.

Let's summarize our data frame with some descriptive statistics to then create a nice chart.

In [121]:
stats = summarizeDF(data, ['Lens','Magnification'], 'PointingTime')
stats

Lens  Magnification         Mean  Count          Std      ci95_hi  \
0    BL              2  1386.135417    480   254.924821  1408.941336   
1    BL              4  1910.610417    480   401.711080  1946.548033   
2    BL              6  2234.925000    480   500.428329  2279.693994   
3    BL             10  3241.764583    480   977.167683  3329.183324   
4    BL             14  4558.591667    480  1437.846583  4687.223365   
5    FL              2  1352.962500    480   278.014521  1377.834055   
6    FL              4  1574.095833    480   289.129836  1599.961779   
7    FL              6  2054.166667    480   457.357867  2095.082519   
8    FL             10  2771.029167    480   724.930586  2835.882436   
9    FL             14  4246.814583    480  1297.639347  4362.903153   
10   ML              2  1164.195833    480   262.794535  1187.705788   
11   ML              4  1826.533333    480   800.365461  1898.135109   
12   ML              6  2370.731250    480   911.937249  2452.314388   
13   ML             10  4817.420833    480  2801.843125  5068.077505   
14   ML             14  7314.062500    480  3824.677542  7656.223320   
15  SCB              2  1484.568750    480   548.585556  1533.645955   
16  SCB              4  1528.547917    480   350.046817  1559.863578   
17  SCB              6  1717.029167    480   419.836546  1754.588311   
18  SCB             10  2072.464583    480   505.087209  2117.650367   
19  SCB             14  2602.666667    480   668.708281  2662.490213   
20  SCF              2  1401.162500    480   231.484225  1421.871392   
21  SCF              4  1654.170833    480   288.018151  1679.937326   
22  SCF              6  2143.287500    480   581.006614  2195.265137   
23  SCF             10  2634.370833    480   641.119991  2691.726294   
24  SCF             14  3966.243750    480  1326.156053  4084.883462   

        ci95_lo  
0   1363.329498  
1   1874.672801  
2   2190.156006  
3   3154.345842  
4   4429.959969  
5   1328.090945  
6   1548.229888  
7   2013.250814  
8   2706.175897  
9   4130.726014  
10  1140.685879  
11  1754.931558  
12  2289.148112  
13  4566.764162  
14  6971.901680  
15  1435.491545  
16  1497.232255  
17  1679.470022  
18  2027.278799  
19  2542.843120  
20  1380.453608  
21  1628.404340  
22  2091.309863  
23  2577.015373  
24  3847.604038

In [124]:
nice_color_palette = ['#f1eef6', '#bdc9e1', '#74a9cf', '#2b8cbe', '#045a8d']
stats['Magnification'] = stats['Magnification'].astype('str')

fig = px.bar(stats, x='Lens', y='Mean', color='Magnification', barmode='group', color_discrete_sequence=nice_color_palette).update_traces(
    error_y={
        'type': 'data',
        'symmetric': False,
        'array': stats['ci95_hi'] - stats['Mean'],
        'arrayminus': stats['Mean'] - stats['ci95_lo'],
    }
)
fig.update_layout({
    'plot_bgcolor' : 'rgba(0,0,0,0)'
})
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGray')

fig.show()

fig.write_image('images/pointingtime_per_lens_magnification.pdf')

## Confidence Intervals of the Mean Difference between two conditions

In [126]:
# compute ttest to compare the 'PointingTime' between FL and ML conditions
ttest = pg.ttest(data_fl['PointingTime'], data_ml['PointingTime'], paired=True)
ttest

T  dof alternative     p-val                CI95%   cohen-d  \
T-test -7.490894    9   two-sided  0.000037  [-1430.59, -766.96]  2.669193   

          BF10  power  
T-test  664.76    1.0

In [127]:
ttest['CI95%']

T-test    [-1430.59, -766.96]
Name: CI95%, dtype: object

In [128]:
print(ttest['CI95%'][0][0], ttest['CI95%'][0][1])

-1430.59 -766.96


In [129]:
desc_fl = data_fl.describe()
desc_fl.loc['mean', 'PointingTime']

2399.8137500000003

In [131]:
desc_ml = data_ml.describe()
desc_ml.loc['mean', 'PointingTime']

3498.5887500000003

In [132]:
diffInMeansFL_ML = desc_ml.loc['mean', 'PointingTime'] - desc_fl.loc['mean', 'PointingTime']

In [133]:
fig = px.scatter(x=[1099], y=['ML-FL'], orientation='h').update_traces(
    error_x={
        'type': 'data',
        'symmetric': False,
        'array': [-766],
        'arrayminus': [-1430],
    }
)
fig.add_vline(x=0)
fig.show()

In [134]:
factor = 'Lens'
measure = 'PointingTime'
participant = 'Participant'

df_CIs = pd.DataFrame(columns = ['PairsOfConditions','DiffInMeans','CI_lo','CI_hi'])
pairsOfConditions = []
diffInMeans = []
ci_lo = []
ci_hi = []

conditions = pd.unique(data[factor])

for i in range(len(conditions)):
    for j in range(len(conditions)):
        if j > i:
            condition1 = conditions[i]
            condition2 = conditions[j]
            data_c1 = data.query(factor+' == \"'+condition1+'\"') # filter out data to get only data for condition 1
            data_c2 = data.query(factor+' == \"'+condition2+'\"') # filter out data to get only data for condition 2
            data_c1 = data_c1.groupby(participant)[[measure]].mean() # aggregate lines to get only one line per participant that contains the mean measure value for that participant and for that condition
            data_c2 = data_c2.groupby(participant)[[measure]].mean()
            ttest = pg.ttest(data_c1[measure], data_c2[measure], paired=True)
            data_c1_stats = data_c1.describe()
            mean_c1 = data_c1_stats.loc['mean', measure]
            data_c2_stats = data_c2.describe()
            mean_c2 = data_c2_stats.loc['mean', measure]
            
            pairsOfConditions = pairsOfConditions + [condition1+'-'+condition2]
            diffInMeans = diffInMeans + [mean_c1-mean_c2]
            ci_lo = ci_lo + [ttest['CI95%'][0][0]]
            ci_hi = ci_hi + [ttest['CI95%'][0][1]]

df_CIs['PairsOfConditions'] = pairsOfConditions
df_CIs['DiffInMeans'] = diffInMeans
df_CIs['CI_lo'] = ci_lo
df_CIs['CI_hi'] = ci_hi

df_CIs

PairsOfConditions  DiffInMeans    CI_lo    CI_hi
0            FL-SCB   518.758333   393.14   644.38
1             FL-ML -1098.775000 -1430.59  -766.96
2             FL-BL  -266.591667  -405.39  -127.80
3            FL-SCF    39.966667  -100.11   180.04
4            SCB-ML -1617.533333 -1988.96 -1246.10
5            SCB-BL  -785.350000  -841.61  -729.09
6           SCB-SCF  -478.791667  -569.85  -387.74
7             ML-BL   832.183333   496.86  1167.51
8            ML-SCF  1138.741667   759.17  1518.31
9            BL-SCF   306.558333   201.41   411.71

In [136]:
fig = px.scatter(df_CIs, x='DiffInMeans', y='PairsOfConditions', orientation='h').update_traces(
    error_x={
        'type': 'data',
        'symmetric': False,
        'array': df_CIs['CI_hi'] - df_CIs['DiffInMeans'],
        'arrayminus': df_CIs['DiffInMeans'] - df_CIs['CI_lo'],
    }
)

fig.add_vline(x=0)

fig.update_layout({
    'plot_bgcolor':'rgba(0,0,0,0)',
    'title':'Comparisons between Pairs of Conditions:',
    'xaxis_title':'Mean Difference between Conditions',
    'yaxis_title':'Pairs of Conditions'
})
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGray')

fig.show()

fig.write_image('images/cis_diff_pairs.pdf')

## Analyzing the effect of a nominal factor with more than two levels on an ordinal measure

This is a case that typically occurs when you collect qualitative appreciations using Likert scales. For example, for each of the technique that participants experienced during the experiment, you ask the following:

<div style='color:#018571'>
How much do you agree (from -2 to 2) with the following statement: <br>
<i>This technique is easy to use</i><br>
(-2: Strongly Disagree, -1: Disagree, 0: Neutral, 1: Agree, 2: Strongly Agree)
</div>

If we keep the same example of the experiment with the five types of magnification lenses that we have mentioned all along, we will typically collect one easy grade per lens and per participant. Let's load these data into a <code>pandas</code> dataframe:

In [137]:
data_likert_full = pd.read_csv('lens_experiment/easy_scores.csv', sep=';')
data_likert_full

Participant  Easy_ML  Easy_FL  Easy_BL  Easy_SCF  Easy_SCB  Unnamed: 6
0            1       -2        0       -1         1         0         NaN
1            2       -1       -2        0         1         1         NaN
2            3       -2       -1        0         0         1         NaN
3            4       -1        0       -1         1         2         NaN
4            5       -2       -2       -1         1         0         NaN
5            6       -2        0        0         1         2         NaN
6            7       -1       -2       -2         0         0         NaN
7            8       -2        0        0         1         2         NaN
8            9       -1        0        0         2         1         NaN
9           10       -1       -1       -1         1         2         NaN

In [138]:
data_likert = data_likert_full.drop('Unnamed: 6',axis = 1)
data_likert = data_likert.drop('Participant',axis = 1)
data_likert = data_likert.rename(columns={'Easy_ML': 'ML', 'Easy_FL': 'FL', 'Easy_BL': 'BL', 'Easy_SCF': 'SCF', 'Easy_SCB': 'SCB'})
data_likert

ML  FL  BL  SCF  SCB
0  -2   0  -1    1    0
1  -1  -2   0    1    1
2  -2  -1   0    0    1
3  -1   0  -1    1    2
4  -2  -2  -1    1    0
5  -2   0   0    1    2
6  -1  -2  -2    0    0
7  -2   0   0    1    2
8  -1   0   0    2    1
9  -1  -1  -1    1    2

We want to test the effect of *Lens* on *EasyScore*. The measure, *EasyScore*, is **not continuous**, it is **ordinal**. When the measure is not continuous, we automatically fall in the **non-parametric** category of statistical tests.

Taking a look at my quidelines regarding which non-parametric test to use (https://pingouin-stats.org/guidelines.html), I can decide on using a Friedman test because:
1. I have more than 2 groups (*i.e.*, I'm comparing five types of lenses)
2. groups are paired because the same participant evaluated each of the five lenses (within-subject design)
3. the measure is not binary, it is a score on a 5-pt Likert scale (5 values).

Note that the Friedman test works with a **wide-format** dataframe, which means that factor levels corresponds to columns.

In [139]:
pg.friedman(data_likert)

Source         W  ddof1          Q     p-unc
Friedman  Within  0.803763      4  32.150538  0.000002

Based on the test report, we can see that *Lens* has a significant effect on *EasyScore* because the p-value is very low (p < 0.001). However, we don't know which types of lenses actually differ. Maybe only one type of lenses is significantly easier to use than the four other ones but the four other ones rated similar regarding their easiness of use? Maybe all lenses signficantly differ from each other?... We can't say based on the sole anova report. To get details about pairs that actually differ, we should run **post-hoc tests**:

In [140]:
# while Friedman test works with a long-format dataframe (one line per observation), posthoc tests work with a wide-format dataframe. Let's load our data again and convert them to wide-format.

data_likert_wide = pd.read_csv('lens_experiment/easy_scores.csv', sep=';')
data_likert_wide = data_likert_wide.drop('Unnamed: 6',axis = 1)
data_likert_wide = data_likert_wide.rename(columns={'Easy_ML': 'ML', 'Easy_FL': 'FL', 'Easy_BL': 'BL', 'Easy_SCF': 'SCF', 'Easy_SCB': 'SCB'})

value_list = list(data_likert_wide.columns)
value_list.remove('Participant')
data_likert_wide
data_likert_long = pd.melt(data_likert_wide, id_vars=['Participant'], var_name='Lens', value_vars=value_list, value_name='EasyScore', ignore_index=False)
data_likert_long


Participant Lens  EasyScore
0            1   ML         -2
1            2   ML         -1
2            3   ML         -2
3            4   ML         -1
4            5   ML         -2
5            6   ML         -2
6            7   ML         -1
7            8   ML         -2
8            9   ML         -1
9           10   ML         -1
0            1   FL          0
1            2   FL         -2
2            3   FL         -1
3            4   FL          0
4            5   FL         -2
5            6   FL          0
6            7   FL         -2
7            8   FL          0
8            9   FL          0
9           10   FL         -1
0            1   BL         -1
1            2   BL          0
2            3   BL          0
3            4   BL         -1
4            5   BL         -1
5            6   BL          0
6            7   BL         -2
7            8   BL          0
8            9   BL          0
9           10   BL         -1
0            1  SCF          1
1            2  SCF          1
2            3  SCF          0
3            4  SCF          1
4            5  SCF          1
5            6  SCF          1
6            7  SCF          0
7            8  SCF          1
8            9  SCF          2
9           10  SCF          1
0            1  SCB          0
1            2  SCB          1
2            3  SCB          1
3            4  SCB          2
4            5  SCB          0
5            6  SCB          2
6            7  SCB          0
7            8  SCB          2
8            9  SCB          1
9           10  SCB          2

In [142]:
posthoc = pg.pairwise_tests(data=data_likert_long, dv='EasyScore', within=['Lens'], subject='Participant', parametric=False, padjust='holm')
posthoc
# gives warnings because our sample size is quite small

/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/_morestats.py:3255: UserWarning:

Exact p-value calculation does not work if there are zeros. Switching to normal approximation.

/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/_morestats.py:3269: UserWarning:

Sample size too small for normal approximation.

/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/_morestats.py:3255: UserWarning:

Exact p-value calculation does not work if there are zeros. Switching to normal approximation.

/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/_morestats.py:3269: UserWarning:

Sample size too small for normal approximation.

/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/_morestats.py:3255: UserWarning:

Exact p-value calculation does not work if there are zeros. Switching to normal approximation.

/opt/anaconda3/lib/python3.9/site-packages/scipy/stats/_morestats.py:3269: UserWarning:

Sample size too small for normal approximation.

/opt/anaconda3/lib/python3.9/si

Contrast    A    B  Paired  Parametric  W-val alternative     p-unc  \
0     Lens   BL   FL    True       False    5.0   two-sided  0.571608   
1     Lens   BL   ML    True       False    3.0   two-sided  0.036359   
2     Lens   BL  SCB    True       False    0.0   two-sided  0.001953   
3     Lens   BL  SCF    True       False    0.0   two-sided  0.006927   
4     Lens   FL   ML    True       False    6.0   two-sided  0.096938   
5     Lens   FL  SCB    True       False    0.0   two-sided  0.007086   
6     Lens   FL  SCF    True       False    0.0   two-sided  0.001953   
7     Lens   ML  SCB    True       False    0.0   two-sided  0.001953   
8     Lens   ML  SCF    True       False    0.0   two-sided  0.001953   
9     Lens  SCB  SCF    True       False   13.5   two-sided  0.529651   

     p-corr p-adjust    hedges  
0  1.000000     holm  0.234599  
1  0.145434     holm  1.392210  
2  0.019531     holm -2.054928  
3  0.041560     holm -2.255883  
4  0.290815     holm  0.895002  
5  0.041560     holm -2.027479  
6  0.019531     holm -2.131774  
7  0.019531     holm -3.445849  
8  0.019531     holm -4.196635  
9  1.000000     holm  0.259599

SCB and SCF are systematically different from BL, FL or ML (all *p's* < 0.05). However, SCB and SCF (p=1) are not significantly different. Neither are BL, FL and ML (all *p's* > 0.05).

As a score on a Likert scale is not continuous, descriptive statistics are not the best way to convey the scores participants gave to the different Lens techniques.

We will now convey participants' answers graphically. We take inspiration from https://www.youtube.com/watch?v=oiITOShYIkA to build a stacked chart that shows the distribution of scores per Lens.

In [143]:
# We first compute how many times each score is given for each Lens:
frequencies = {}
for i in data_likert.columns:
    frequencies[i] = data_likert[i].value_counts()
frequencies

{'ML': -2    5
 -1    5
 Name: ML, dtype: int64,
 'FL':  0    5
 -2    3
 -1    2
 Name: FL, dtype: int64,
 'BL':  0    5
 -1    4
 -2    1
 Name: BL, dtype: int64,
 'SCF': 1    7
 0    2
 2    1
 Name: SCF, dtype: int64,
 'SCB': 2    4
 0    3
 1    3
 Name: SCB, dtype: int64}

In [144]:
plotdata = pd.DataFrame(frequencies)
# the data frame contains 'NaN' when the frequency is 0 for one type of observation. We turn NaNs into zeros:
plotdata = plotdata.fillna(0)
# we transpose the data frame (turn lines into columns and vice versa) to get the right input format for our chart
plotdata = plotdata.transpose()
plotdata

-2   -1    0    1    2
ML   5.0  5.0  0.0  0.0  0.0
FL   3.0  2.0  5.0  0.0  0.0
BL   1.0  4.0  5.0  0.0  0.0
SCF  0.0  0.0  2.0  7.0  1.0
SCB  0.0  0.0  3.0  3.0  4.0

In [145]:
# our column headers are of type 'int64', which prevents us from renaming them with string labels
# we first change the type of those column names to string
plotdata.columns = plotdata.columns.astype(str)
scoreLabels = {'-2':'Strongly Disagree', '-1':'Disagree', '0':'Neither Disagree or Agree', '1':'Agree', '2':'Strongly Agree'}
plotdata = plotdata.rename(columns=scoreLabels)
plotdata

Strongly Disagree  Disagree  Neither Disagree or Agree  Agree  \
ML                 5.0       5.0                        0.0    0.0   
FL                 3.0       2.0                        5.0    0.0   
BL                 1.0       4.0                        5.0    0.0   
SCF                0.0       0.0                        2.0    7.0   
SCB                0.0       0.0                        3.0    3.0   

     Strongly Agree  
ML              0.0  
FL              0.0  
BL              0.0  
SCF             1.0  
SCB             4.0

In [146]:
fig = px.bar(plotdata, orientation='h')
fig.update_layout(barmode='stack')
fig.show()

In [147]:
# turn frequency counts into percentages
participantCount = len(data_likert_full['Participant'].values)
plotdataproportion = plotdata/participantCount

# create the chart, adjusting some of its properties to make it look nice!
fig = px.bar(plotdataproportion, orientation='h', color_discrete_sequence=['#a6611a', '#d2b08c', '#b3b3b3', '#80c2b8', '#018571'], text_auto=".0%")
fig.update_layout({
    'barmode':'stack',
    'title':'The technique is easy to use:',
    'xaxis_title':'Cumulative percentage',
    'yaxis_title':'Technique',
    'legend_title':'Answer',
    'xaxis':dict(
        tickmode = 'array',
        tickvals = [0, 0.2, 0.4, 0.6, 0.8, 1],
        ticktext = [0, 20, 40, 60, 80, 1]
    ),
    'plot_bgcolor':'rgba(0,0,0,0)'
})

fig.show()